FROM python:3.7

RUN pip install --upgrade pip && \
    pip install torch==1.7.1+cpu torchvision==0.8.2+cpu torchaudio==0.7.2 torchserve torch-model-archiver -f https://download.pytorch.org/whl/torch_stable.html && \
    pip install --no-cache-dir numpy mlflow transformers==3.5.0 sklearn tqdm torchtext pandas cloudpickle boto3

